version: "3.8"

services:
  traefik:
    image: traefik:v3.1
    command:
      # Provider (Docker-Integration)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # HTTP (Port 80) → Weiterleitung auf HTTPS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # HTTPS (Port 443)
      - "--entrypoints.websecure.address=:443"

      # Let's Encrypt Einstellungen
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=franzhielscher1@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"

      # Logging (optional)
      - "--log.level=INFO"

      - "--serverstransport.insecureskipverify=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    restart: unless-stopped

  web:
    build: .
    container_name: web
    volumes:
      - ./public:/var/www/html
    labels:
      - "traefik.enable=true"

      # Domain-Regel (jetzt korrekt mit OR statt Komma)
      - "traefik.http.routers.web.rule=Host(`franzhielscher.studio`) || Host(`www.franzhielscher.studio`)"

      # EntryPoint & SSL-Zertifikat
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=le"

      # (Optional) HSTS + Redirects
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    depends_on:
      - db
    environment:
      SMTP_USER: "franzhielscher1@gmail.com"
      SMTP_PASS: "puhy fpdg kbww gvzr"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
