version: "3.8"

services:
  web:
    build: .
    container_name: web
    volumes:
      - ./public:/var/www/html
    ports:
      - "8080:80"
    environment:
      SMTP_USER: "franzhielscher1@gmail.com"
      SMTP_PASS: "puhy fpdg kbww gvzr"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
